= Python Language New Features
:author: Thamme Gowda <tgowdan@gmail.com>
1.0, September 27, 2022: Python New Features
:toc:
:icons: font
:source-highlighter: highlight.js


For a long time I have been stuck at v3.7. This document is for educating myself about new features of Python language. 

Focusing on new syntax features and helpful utilities.

== 3.11

IMPORTANT: Python 3.11 is between 10-60% faster than Python 3.10. If you dont have a preference for older Python (3.10-), just upgrade.

Full list: https://docs.python.org/3.11/whatsnew/3.11.html

===  TypedDict
```python
class Movie(TypedDict):
   title: str
   year: NotRequired[int]

m1: Movie = {"title": "Black Panther", "year": 2018}  # OK
m2: Movie = {"title": "Star Wars"}  # OK (year is not required)
m3: Movie = {"year": 2022}  # ERROR (missing required field title)

## also this

class Movie(TypedDict, total=False):
   title: Required[str]
   year: int

```
=== Self type

```python
class MyLock:
    def __enter__(self) -> Self:
        self.lock()
        return self

    ...

class MyInt:
    @classmethod
    def fromhex(cls, s: str) -> Self:
        return cls(int(s, 16))
```

=== Dataclass Transforms
```python
# The create_model decorator is defined by a library.
@typing.dataclass_transform()
def create_model(cls: Type[T]) -> Type[T]:
    cls.__init__ = ...
    cls.__eq__ = ...
    cls.__ne__ = ...
    return cls

# The create_model decorator can now be used to create new model classes:
@create_model
class CustomerModel:
    id: int
    name: str

c = CustomerModel(id=327, name="Eric Idle")
```
=== `tomllib` is in Standard Lib 

Now you can parse and produce TOML without a 3rd party dependency

https://docs.python.org/3.11/library/tomllib.html#module-tomllib




== 3.10 

:link:https://docs.python.org/3.10/whatsnew/3.10.html

=== Structural pattern matching 
```python
def http_error(status):
    match status:
        case 400:
            return "Bad request"
        case 404:
            return "Not found"
        case 418:
            return "I'm a teapot"
        case _:
            return "Something's wrong with the internet"
```

=== Union of types as `X|Y` (previously, typing.Union[X, Y])
```python
def greet_all(names: list[str]) -> None:
    for name in names:
        print("Hello", name)

```


=== Context manager with paranthesis
```python
with (
    CtxManager1() as example1,
    CtxManager2() as example2,
    CtxManager3() as example3,
):
```
=== `zip` has `strict` argument to enfore same lenghts


== 3.9 

:link:https://docs.python.org/3.9/whatsnew/3.9.html

=== Dictionary merge and update `a|b` or `a|=b`

```python
>>> x = {"key1": "value1 from x", "key2": "value2 from x"}
>>> y = {"key2": "value2 from y", "key3": "value3 from y"}
>>> x | y
{'key1': 'value1 from x', 'key2': 'value2 from y', 'key3': 'value3 from y'}
>>> y | x
{'key2': 'value2 from x', 'key3': 'value3 from y', 'key1': 'value1 from x'}
```

=== Type hinting generics in standard collections: `list[str]`, `dict[str, int]` 

== 3.8 

:link:https://docs.python.org/3.8/whatsnew/3.8.html 

=== Assignment expression aka walrus operator `:=`
```python
# re search
discount = 0.0
if (mo := re.search(r'(\d+)% discount', advertisement)):
    discount = float(mo.group(1)) / 100.0

# loop 
while (block := f.read(256)) != '':
    process(block)
```

=== Position only parameters seperated by `/`
```python
# a, b must be specified as position only
def f(a, b, /, c, d, *, e, f):
    print(a, b, c, d, e, f)
```
=== f-strings support `=` for self-documenting expressions
```python
>>>user = 'eric_idle'
>>>member_since = date(1975, 7, 31)
>>>f'{user=} {member_since=}'
"user='eric_idle' member_since=datetime.date(1975, 7, 31)"

# format specifiers
>>> delta = date.today() - member_since
>>> f'{user=!s}  {delta.days=:,d}'
'user=eric_idle  delta.days=16,075'
```
=== `asyncio.run()` is now a stable API

~~~

TODO: for 3.5 and lower 


